don't detect package.json as this is a sencha file

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,10 +1,12 @@
 #!/usr/bin/env bash
 # bin/detect <build-dir>
 
-if [ -f $1/package.json ]; then
-  echo 'Node.js'
-  exit 0
-fi
+#if [ -f $1/package.json ]; then
+#  echo 'Node.js'
+#  exit 0
+#fi
 
->&2 echo 'Node.js: package.json not found in application root'
-exit 1
+exit 0
+
+#>&2 echo 'Node.js: package.json not found in application root'
+#exit 1
